export const PivotTableRendererType = {
  TABLE: 'TABLE',
  TABLE_BARCHART: 'TABLE_BARCHART',
  HEATMAP: 'HEATMAP',
  ROW_HEATMAP: 'ROW_HEATMAP',
  COL_HEATMAP: 'COL_HEATMAP',
  TREEMAP: 'TREEMAP',
  LINE_CHART: 'LINE_CHART',
  BAR_CHART: 'BAR_CHART',
  STACKED_BAR_CHART: 'STACKED_BAR_CHART',
  AREA_CHART: 'AREA_CHART',
  SCATTER_CHART: 'SCATTER_CHART',
  TSV_EXPORT: 'TSV_EXPORT'
}
