export class KeyboardShortcutDescription {

  NAME: KeyboardShortcutName;
  keyboardShortcuts: string[] = [];
  //@ts-ignore
  executeFunction: (yasqe: Yasqe) => void
}

export enum KeyboardShortcutName {
  TRIGGER_AUTOCOMPLETION = 'TRIGGER_AUTOCOMPLETION',
  DELETE_CURRENT_LINE = 'DELETE_CURRENT_LINE',
  COMMENT_SELECTED_LINE = 'COMMENT_SELECTED_LINE',
  COPY_LINE_DOWN = 'COPY_LINE_DOWN',
  COPY_LINE_UP = 'COPY_LINE_UP',
  AUTO_FORMAT_SELECTED_LINE = 'AUTO_FORMAT_SELECTED_LINE',
  INDENT_CURRENT_LINE_MORE = 'INDENT_CURRENT_LINE_MORE',
  INDENT_CURRENT_LINE_LESS = 'INDENT_CURRENT_LINE_LESS',
  EXECUTE_QUERY_OR_UPDATE = 'EXECUTE_QUERY_OR_UPDATE',
  EXECUTE_EXPLAIN_PLAN_FOR_QUERY = 'EXECUTE_EXPLAIN_PLAN_FOR_QUERY',
  CREATE_TAB = 'CREATE_TAB',
  CREATE_SAVE_QUERY = 'CREATE_SAVE_QUERY',
  SWITCH_NEXT_TAB = 'SWITCH_NEXT_TAB',
  SWITCH_PREVIOUS_TAB = 'SWITCH_PREVIOUS_TAB',
  CLOSES_ALL_TABS = 'CLOSES_ALL_TABS',
  F11 = 'F11',
  ESC = 'ESC'
}
