/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { YasguiConfiguration } from "./models/yasgui-configuration";
import { QueryEvent, QueryResponseEvent } from "./models/event";
export namespace Components {
    interface OntotextYasgui {
        /**
          * An input object property containing the yasgui configuration.
         */
        "config": YasguiConfiguration;
        "setQuery": (query: string) => Promise<void>;
    }
}
export interface OntotextYasguiCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLOntotextYasguiElement;
}
declare global {
    interface HTMLOntotextYasguiElement extends Components.OntotextYasgui, HTMLStencilElement {
    }
    var HTMLOntotextYasguiElement: {
        prototype: HTMLOntotextYasguiElement;
        new (): HTMLOntotextYasguiElement;
    };
    interface HTMLElementTagNameMap {
        "ontotext-yasgui": HTMLOntotextYasguiElement;
    }
}
declare namespace LocalJSX {
    interface OntotextYasgui {
        /**
          * An input object property containing the yasgui configuration.
         */
        "config"?: YasguiConfiguration;
        /**
          * Event emitted when before query to be executed.
         */
        "onQueryExecuted"?: (event: OntotextYasguiCustomEvent<QueryEvent>) => void;
        /**
          * Event emitted when after query response is returned.
         */
        "onQueryResponse"?: (event: OntotextYasguiCustomEvent<QueryResponseEvent>) => void;
    }
    interface IntrinsicElements {
        "ontotext-yasgui": OntotextYasgui;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ontotext-yasgui": LocalJSX.OntotextYasgui & JSXBase.HTMLAttributes<HTMLOntotextYasguiElement>;
        }
    }
}
